version: '3.8'

services:
  app:
    container_name: qdrant-api
    image: vontainment/gpt-qdrant-api:latest  # Use your appropriate image
    hostname: qdrant-api
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8077:80"
    depends_on:
      - qdrant
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_API_KEY: YOUR_QDRANT_API_KEY
      OPENAI_API_KEY: YOUR_OPENAI_API_KEY

  qdrant:
    image: generall/qdrant
    environment:
      API_KEY: YOUR_QDRANT_API_KEY

volumes:
  qdrant_data:
