version: '3.8'
services:
  memories-api:
    container_name: memories-api
    image: vontainment/v-gpt-qdrant-api:dev # Use your appropriate image
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8060:8060"
    environment:
      QDRANT_HOST: http://qdrant:6333
      QDRANT_API_KEY:
      #MEMORIES_API_KEY: Optional API key to connect to api
      BASE_URL: http://memories-api
      WORKERS: 1 #uvicorn workers 1 should be enough for personal use
      API_CONCURRENCY: 4 #max embeddings produced similtaniusly. This stops eccessive CPU usage. 
      UVICORN_CONCURRENCY: 32 #this controls the mac connections. Anything over the API_concurrancy value is put in query pool. Anything over this number is rejected.
    volumes:
      - embedding-model:/tmp/fastembed_cache

  qdrant:
    image: langgenius/qdrant:latest
    container_name: qdrant
    restart: always
    #ports:
       #- "8060:6333"
    environment:
      QDRANT_API_KEY:
    volumes:
      - qdrant-data:/qdrant/storage
      - qdrant-config:/qdrant/config/

volumes:
  embedding-model:
  qdrant-data:
  qdrant-config:
