version: '3.8'

services:
  app:
    container_name: qdrant-api
    image: vontainment/gpt-qdrant-api:main # Use your appropriate image
    hostname: qdrant-api
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8077:80"
    depends_on:
      - qdrant
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDINGS_MODEL: text-embedding-3-large
      QDRANT_HOST: qdrant
      QDRANT_API_KEY: xtfpouszukodiivuaucbgeozlzlwdwac
      BASE_URL: http://qdrant-api

  qdrant:
    image: generall/qdrant
    environment:
      API_KEY: xtfpouszukodiivuaucbgeozlzlwdwac

volumes:
  qdrant_data:
