version: '3.8'
services:
  memories-api:
    container_name: memories-api
    image: vontainment/v-gpt-qdrant-api:dev # Use your appropriate image
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8060:8060"
    environment:
      QDRANT_HOST: http://qdrant:6333
      QDRANT_API_KEY:
      #MEMORIES_API_KEY:
      BASE_URL: http://memories-api
      WORKERS: 1
      MAX_REQUESTS: 128
      MAX_REQUESTS_JITTER: 16
      LIMIT_CONCURRENCY: 5
      LIMIT_CONCURRENCY_JITTER: 3
    volumes:
      - embedding-model:/tmp/fastembed_cache

  qdrant:
    image: langgenius/qdrant:latest
    container_name: qdrant
    restart: always
    #ports:
       #- "8060:6333"
    environment:
      QDRANT_API_KEY:
    volumes:
      - qdrant-data:/qdrant/storage
      - qdrant-config:/qdrant/config/

volumes:
  embedding-model:
  qdrant-data:
  qdrant-config:
