version: '3.8'
services:
  app:
  memories-api:
    container_name: memories-api
    image: vontainment/v-gpt-qdrant-api:main # Use your appropriate image
    restart: always
    depends_on:
      - memories-db
    ports:
      - "8077:80"
    environment:
      QDRANT_HOST: qdrant
      QDRANT_API_KEY: xtfpouszusdsdsozlzlwdwac
      MEMORY_API_KEY:
      EMBEDDING_API_KEY:
      BASE_URL: http://qdrant-api
    volumes:
      - embedding-model:/app/model
      
  memories-db:
    image: qdrant/qdrant:latest
    container_name: memories-db
    restart: always
    environment:
      QDRANT_API_KEY: xtfpouszusdsdsozlzlwdwac
    volumes:
      - memories-data:/qdrant/storage

volumes:
  embedding-model:
  memories-data:
