version: '3.8'
services:
  app:
  memories-api:
    container_name: memories-api
    image: vontainment/v-gpt-qdrant-api:main # Use your appropriate image
    restart: always
    depends_on:
      - memories-db
    ports:
      - "8050:80"
    environment:
      QDRANT_HOST: http://memories-db:6333
      QDRANT_API_KEY:
      #MEMORIES_API_KEY:
      BASE_URL: http://memories-api
      UVICORN_WORKERS: 3
    volumes:
      - embedding-model:/tmp/fastembed_cache

  memories-db:
    image: langgenius/qdrant:latest
    container_name: memories-db
    restart: always
    #ports:
       #- "8060:6333"
    environment:
      QDRANT_API_KEY:
    volumes:
      - memories-data:/qdrant/storage
      - qdrant-config:/qdrant/config/

volumes:
  embedding-model:
  memories-data:
  qdrant-config:
